// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'bread': string;
  'clicked': string;
  'dot': string;
  'duck-trail': string;
  'duck-trail2': string;
  'duck1': string;
  'duck2': string;
  'eat1': string;
  'eat1Circle': string;
  'eat2Circle': string;
  'eatAnimation': string;
  'eating': string;
  'food': string;
  'game_container': string;
  'game_div': string;
  'knowBtn': string;
  'line': string;
  'line2': string;
  'loseImg': string;
  'moveForward': string;
  'moveLeftRight': string;
  'moving': string;
  'object': string;
  'outLine': string;
  'playing': string;
  'rePlayBtn': string;
  'resultReplayBtn': string;
  'resultText': string;
  'resultText2': string;
  'rule1': string;
  'ruleText': string;
  'startBtn': string;
  'startDot': string;
  'text': string;
  'tipBtn': string;
  'tipImg': string;
  'unLogin': string;
  'unLogin_bg': string;
  'water_div': string;
  'winImg': string;
  'zoomIn': string;
}
export const cssExports: CssExports;
export default cssExports;
